### ISSUE TITLE
pycurl SSL certificate problem (on Windows)

### ISSUE THREAD

**Issue by aleksanh** [siznax/wptools#20] opened 2016-09-20 17:58 UTC
After installing via pip and start testing with: 
import wptools

a = wptools.page('usa')

i always get: 
>>> a.get()
en.wikipedia.org (action=query) USA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\wptools\core.py", line 460, in get
    self.get_query(show=False)
  File "C:\Anaconda2\lib\site-packages\wptools\core.py", line 547, in get_query
    query['response'] = self.__fetch.curl(qry)
  File "C:\Anaconda2\lib\site-packages\wptools\fetch.py", line 109, in curl
    return self.curl_perform(crl)
  File "C:\Anaconda2\lib\site-packages\wptools\fetch.py", line 117, in curl_perform
    crl.perform()
pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')

or

>>> a.get()
en.wikipedia.org (action=query) USA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\wptools\core.py", line 460, in get
    self.get_query(show=False)
  File "C:\Anaconda2\lib\site-packages\wptools\core.py", line 547, in get_query
    query['response'] = self.__fetch.curl(qry)
  File "C:\Anaconda2\lib\site-packages\wptools\fetch.py", line 109, in curl
    return self.curl_perform(crl)
  File "C:\Anaconda2\lib\site-packages\wptools\fetch.py", line 117, in curl_perf
orm
    crl.perform()
pycurl.error: (28, 'Resolving timed out after 15007 milliseconds')

Any hints of where to go from her ?

**Comment by siznax** [comment] 2016-09-20 18:55
Hi @aleksanh, thanks for reporting this. This is happening because all of our MediaWiki API queries are using HTTPS and for some reason, on your system, pycurl is unable to verify. I pushed a patch (be69afc0b72957045a7aa36e11a6f43d8f8353df) and rolled a new rev ([0.1.7](https://pypi.python.org/pypi/wptools/0.1.7)) which uses [`python-cerifi`](https://github.com/certifi/python-certifi) to provide local SSL certs.

If you upgrade `wptools` does it work for you?

```
pip install -U wptools
```

You can verify your version with:

```
>>> import wptools
>>> wptools.__version__
'0.1.7'
```

**Comment by aleksanh** [comment] 2016-09-20 19:01
Hi Steve and thanks for the quick replay.

it seems that the requiirments are not up to date ? se the stack trace:

  ** make sure the development packages of libxml2 and libxslt are
installed **

  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\lxml
  copying src\lxml\builder.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\cssselect.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\doctestcompare.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\ElementInclude.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\sax.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\usedoctest.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\_elementpath.py -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\__init__.py -> build\lib.win-amd64-2.7\lxml
  creating build\lib.win-amd64-2.7\lxml\includes
  copying src\lxml\includes\__init__.py ->
build\lib.win-amd64-2.7\lxml\includes

  creating build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\builder.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\clean.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\defs.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\diff.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\formfill.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\html5parser.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\soupparser.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\_html5builder.py ->
build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-2.7\lxml\html
  copying src\lxml\html\__init__.py -> build\lib.win-amd64-2.7\lxml\html
  creating build\lib.win-amd64-2.7\lxml\isoschematron
  copying src\lxml\isoschematron\__init__.py ->
build\lib.win-amd64-2.7\lxml\iso
schematron
  copying src\lxml\lxml.etree.h -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-2.7\lxml
  copying src\lxml\includes\c14n.pxd ->
build\lib.win-amd64-2.7\lxml\includes
  copying src\lxml\includes\config.pxd ->
build\lib.win-amd64-2.7\lxml\includes
  copying src\lxml\includes\dtdvalid.pxd ->
build\lib.win-amd64-2.7\lxml\include
s
  copying src\lxml\includes\etreepublic.pxd ->
build\lib.win-amd64-2.7\lxml\incl
udes
  copying src\lxml\includes\htmlparser.pxd ->
build\lib.win-amd64-2.7\lxml\inclu
des
  copying src\lxml\includes\relaxng.pxd ->
build\lib.win-amd64-2.7\lxml\includes

  copying src\lxml\includes\schematron.pxd ->
build\lib.win-amd64-2.7\lxml\inclu
des
  copying src\lxml\includes\tree.pxd ->
build\lib.win-amd64-2.7\lxml\includes
  copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-2.7\lxml\includes
  copying src\lxml\includes\xinclude.pxd ->
build\lib.win-amd64-2.7\lxml\include
s
  copying src\lxml\includes\xmlerror.pxd ->
build\lib.win-amd64-2.7\lxml\include
s
  copying src\lxml\includes\xmlparser.pxd ->
build\lib.win-amd64-2.7\lxml\includ
es
  copying src\lxml\includes\xmlschema.pxd ->
build\lib.win-amd64-2.7\lxml\includ
es
  copying src\lxml\includes\xpath.pxd ->
build\lib.win-amd64-2.7\lxml\includes
  copying src\lxml\includes\xslt.pxd ->
build\lib.win-amd64-2.7\lxml\includes
  copying src\lxml\includes\etree_defs.h ->
build\lib.win-amd64-2.7\lxml\include
s
  copying src\lxml\includes\lxml-version.h ->
build\lib.win-amd64-2.7\lxml\inclu
des
  creating build\lib.win-amd64-2.7\lxml\isoschematron\resources
  creating build\lib.win-amd64-2.7\lxml\isoschematron\resources\rng
  copying src\lxml\isoschematron\resources\rng\iso-schematron.rng ->
build\lib.w
in-amd64-2.7\lxml\isoschematron\resources\rng
  creating build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl ->
build\lib.win-a
md64-2.7\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl ->
build\lib.win-a
md64-2.7\lxml\isoschematron\resources\xsl
  creating
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematr
on-xslt1
  copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract
_expand.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-sche
matron-xslt1
  copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_inc
lude.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schemat
ron-xslt1
  copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematr
on_message.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-s
chematron-xslt1
  copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematr
on_skeleton_for_xslt1.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resource
s\xsl\iso-schematron-xslt1
  copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for
_xslt1.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schem
atron-xslt1
  copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -
>
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  creating build\temp.win-amd64-2.7\Release\src\lxml
  C:\Users\aleksanh\AppData\Local\Programs\Common\Microsoft\Visual C++ for
Pytho
n\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
-Isrc\lxml\includ
es -IC:\Anaconda2\include -IC:\Anaconda2\PC /Tcsrc\lxml\lxml.etree.c
/Fobuild\te
mp.win-amd64-2.7\Release\src\lxml\lxml.etree.obj -w
  cl : Command line warning D9025 : overriding '/W3' with '/w'
  lxml.etree.c
  src\lxml\includes\etree_defs.h(14) : fatal error C1083: Cannot open
include fi
le: 'libxml/xmlversion.h': No such file or directory
  Compile failed: command
'C:\\Users\\aleksanh\\AppData\\Local\\Programs\\Common
\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed
with exi
t status 2
  creating users
  creating users\aleksanh
  creating users\aleksanh\appdata
  creating users\aleksanh\appdata\local
  creating users\aleksanh\appdata\local\temp
  C:\Users\aleksanh\AppData\Local\Programs\Common\Microsoft\Visual C++ for
Pytho
n\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
-I/usr/include/li
bxml2 /Tcc:\users\aleksanh\appdata\local\temp\xmlXPathInitou7s11.c
/Fousers\alek
sanh\appdata\local\temp\xmlXPathInitou7s11.obj
  xmlXPathInitou7s11.c
  c:\users\aleksanh\appdata\local\temp\xmlXPathInitou7s11.c(1) : fatal
error C10
83: Cannot open include file: 'libxml/xpath.h': No such file or directory

******************************************************************************
***
  Could not find function xmlCheckVersion in library libxml2. Is libxml2
install
ed?

******************************************************************************
***
  error: command
'C:\\Users\\aleksanh\\AppData\\Local\\Programs\\Common\\Microso
ft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit
status
2

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml, wptools
  Found existing installation: lxml 3.6.0
    Uninstalling lxml-3.6.0:
      Successfully uninstalled lxml-3.6.0
  Running setup.py install for lxml ... error
    Complete output from command C:\Anaconda2\python.exe -u -c "import
setuptool
s,
tokenize;__file__='c:\\users\\aleksanh\\appdata\\local\\temp\\pip-build-dmo8g
2\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open',
open)(__file__).read()
.replace('\r\n', '\n'), __file__, 'exec'))" install --record
c:\users\aleksanh\a
ppdata\local\temp\pip-vrbg1c-record\install-record.txt
--single-version-external
ly-managed --compile:
    Building lxml version 3.6.4.
    Building without Cython.
    ERROR: 'xslt-config' is not recognized as an internal or external
command,
    operable program or batch file.

    ** make sure the development packages of libxml2 and libxslt are
installed *
*

    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\lxml
    copying src\lxml\builder.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\cssselect.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\sax.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\usedoctest.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\_elementpath.py -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\__init__.py -> build\lib.win-amd64-2.7\lxml
    creating build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\__init__.py ->
build\lib.win-amd64-2.7\lxml\includ
es
    creating build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\ElementSoup.py ->
build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\html5parser.py ->
build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\_diffcommand.py ->
build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\_html5builder.py ->
build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-2.7\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win-amd64-2.7\lxml\html
    creating build\lib.win-amd64-2.7\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py ->
build\lib.win-amd64-2.7\lxml\i
soschematron
    copying src\lxml\lxml.etree.h -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-2.7\lxml
    copying src\lxml\includes\c14n.pxd ->
build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\config.pxd ->
build\lib.win-amd64-2.7\lxml\include
s
    copying src\lxml\includes\dtdvalid.pxd ->
build\lib.win-amd64-2.7\lxml\inclu
des
    copying src\lxml\includes\etreepublic.pxd ->
build\lib.win-amd64-2.7\lxml\in
cludes
    copying src\lxml\includes\htmlparser.pxd ->
build\lib.win-amd64-2.7\lxml\inc
ludes
    copying src\lxml\includes\relaxng.pxd ->
build\lib.win-amd64-2.7\lxml\includ
es
    copying src\lxml\includes\schematron.pxd ->
build\lib.win-amd64-2.7\lxml\inc
ludes
    copying src\lxml\includes\tree.pxd ->
build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\uri.pxd ->
build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\xinclude.pxd ->
build\lib.win-amd64-2.7\lxml\inclu
des
    copying src\lxml\includes\xmlerror.pxd ->
build\lib.win-amd64-2.7\lxml\inclu
des
    copying src\lxml\includes\xmlparser.pxd ->
build\lib.win-amd64-2.7\lxml\incl
udes
    copying src\lxml\includes\xmlschema.pxd ->
build\lib.win-amd64-2.7\lxml\incl
udes
    copying src\lxml\includes\xpath.pxd ->
build\lib.win-amd64-2.7\lxml\includes

    copying src\lxml\includes\xslt.pxd ->
build\lib.win-amd64-2.7\lxml\includes
    copying src\lxml\includes\etree_defs.h ->
build\lib.win-amd64-2.7\lxml\inclu
des
    copying src\lxml\includes\lxml-version.h ->
build\lib.win-amd64-2.7\lxml\inc
ludes
    creating build\lib.win-amd64-2.7\lxml\isoschematron\resources
    creating build\lib.win-amd64-2.7\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng ->
build\lib
.win-amd64-2.7\lxml\isoschematron\resources\rng
    creating build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl ->
build\lib.win
-amd64-2.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl ->
build\lib.win
-amd64-2.7\lxml\isoschematron\resources\xsl
    creating
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schema
tron-xslt1
    copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstra
ct_expand.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-sc
hematron-xslt1
    copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_i
nclude.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schem
atron-xslt1
    copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schema
tron_message.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso
-schematron-xslt1
    copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schema
tron_skeleton_for_xslt1.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resour
ces\xsl\iso-schematron-xslt1
    copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_f
or_xslt1.xsl ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-sch
ematron-xslt1
    copying
src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt
 ->
build\lib.win-amd64-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt
1
    running build_ext
    building 'lxml.etree' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\src
    creating build\temp.win-amd64-2.7\Release\src\lxml
    C:\Users\aleksanh\AppData\Local\Programs\Common\Microsoft\Visual C++
for Pyt
hon\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
-Isrc\lxml\incl
udes -IC:\Anaconda2\include -IC:\Anaconda2\PC /Tcsrc\lxml\lxml.etree.c
/Fobuild\
temp.win-amd64-2.7\Release\src\lxml\lxml.etree.obj -w
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    lxml.etree.c
    src\lxml\includes\etree_defs.h(14) : fatal error C1083: Cannot open
include
file: 'libxml/xmlversion.h': No such file or directory
    Compile failed: command
'C:\\Users\\aleksanh\\AppData\\Local\\Programs\\Comm
on\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed
with e
xit status 2
    C:\Users\aleksanh\AppData\Local\Programs\Common\Microsoft\Visual C++
for Pyt
hon\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
-I/usr/include/
libxml2 /Tcc:\users\aleksanh\appdata\local\temp\xmlXPathInitgif5u9.c
/Fousers\al
eksanh\appdata\local\temp\xmlXPathInitgif5u9.obj
    xmlXPathInitgif5u9.c
    c:\users\aleksanh\appdata\local\temp\xmlXPathInitgif5u9.c(1) : fatal
error C
1083: Cannot open include file: 'libxml/xpath.h': No such file or directory

****************************************************************************
*****
    Could not find function xmlCheckVersion in library libxml2. Is libxml2
insta
lled?

****************************************************************************
*****
    error: command
'C:\\Users\\aleksanh\\AppData\\Local\\Programs\\Common\\Micro
soft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit
statu
s 2

    ----------------------------------------
  Rolling back uninstall of lxml
Command "C:\Anaconda2\python.exe -u -c "import setuptools,
tokenize;__file__='c:
\\users\\aleksanh\\appdata\\local\\temp\\pip-build-dmo8g2\\lxml\\setup.py';exec(
compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n',
'\n'),
__file__, 'exec'))" install --record
c:\users\aleksanh\appdata\local\temp\pip-vr
bg1c-record\install-record.txt --single-version-externally-managed
--compile" fa
iled with error code 1 in
c:\users\aleksanh\appdata\local\temp\pip-build-dmo8g2\
lxml\

2016-09-20 20:55 GMT+02:00 Steve <notifications@github.com>:

**Comment by siznax** [comment] 2016-09-20 19:13
Hmm. @aleksanh, can you try with a fresh `virtualenv`?

```bash
$ mkvirtualenv wptools_test
[wptools_test] $ pip install wptools
...
Successfully installed certifi-2016.8.31 html2text-2016.9.19 html5lib-0.999999999 lxml-3.6.4 pycurl-7.43.0 requests-2.11.1 six-1.10.0 webencodings-0.5 wptools-0.1.7
```

**Comment by aleksanh** [comment] 2016-09-20 19:17
Hi @siznax , Do you have a windows equalient command for: $ mkvirtualenv wptools_test ?

**Comment by siznax** [comment] 2016-09-20 19:18
Hehe, how about https://pypi.python.org/pypi/virtualenvwrapper-win? Good luck!

**Comment by aleksanh** [comment] 2016-09-20 19:24
@siznax 
$ mkvirtualenv wptools_test == Sucsses
how ever (wptools_test) C:\> pip install wptools == Same failure as above....

**Comment by siznax** [comment] 2016-09-20 19:27
Hmm. @aleksanh does this SO answer help you at all? http://stackoverflow.com/questions/33785755

**Comment by aleksanh** [comment] 2016-09-20 19:37
uhm @siznax se her http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml as it says in the text :
The binaries are compatible with the official CPython distribution on Windows >=6.0. Chances are they do not work with custom Python distributions included with Blender, Maya, ArcGIS, OSGeo4W, ABAQUS, Cygwin, Pythonxy, Canopy, EPD, Anaconda, WinPython etc. Many binaries are not compatible with Windows XP or Wine.

I am using a Anaconda distrubution, and i have had other strang issues with my python of late. will do more digging tomorrow when the light is brighter.....

**Comment by siznax** [comment] 2016-09-20 19:39
Okay, good luck @aleksanh.

**Comment by siznax** [comment] 2016-10-05 21:20
No word on this from @aleksanh for a while, so closing as can't reproduce.

**Closed by siznax** 2016-10-05 21:20 UTC
Labels: Bug
