### ISSUE TITLE
TypeError on Windows 10

### ISSUE THREAD

**Issue by Kiwibp** [siznax/wptools#95] opened 2017-12-13 20:57 UTC
[https://stackoverflow.com/questions/47801943/wptools-wikipedia-api-bug](https://stackoverflow.com/questions/47801943/wptools-wikipedia-api-bug)

I am a beginner level programmer and just following the process of submitting an issue is over my head so my apologies for not following procedure but if anyone can clarify whats going on here it would be much appreciated.  Thanks!

**Comment by siznax** [comment] 2017-12-13 21:15
Thanks for trying wptools, @Kiwibp. From your SO question:

```python
>>> import wptools
>>> wptools.page('E.T._the_Extra-Terrestrial').get()

TypeError: the JSON object must be str, not 'bytes'
```

I can't reproduce this. Can you give us more of the error message? The `get()` method is a convenience function that calls `get_query()`, `get_parse()`, etc. Maybe try one of those methods and post the full output here, like this:

```python
>>> page = wptools.page('E.T._the_Extra-Terrestrial')
>>> page.get_query()
en.wikipedia.org (query) E.T._the_Extra-Terrestrial
en.wikipedia.org (imageinfo) File:E t the extra terrestrial ver3.jpg
E.T. the Extra-Terrestrial (en) data
...
```

**Comment by Kiwibp** [comment] 2017-12-13 21:30
Thanks for the quick response! Both of those methods still give me the same error:

TypeErrorTraceback (most recent call last)
<ipython-input-58-64409432cf2d> in <module>()
      1 # Your code here: get the E.T. page object
      2 # This cell make take a few seconds to run
----> 3 page = wptools.page('E.T._the_Extra-Terrestrial').get()
      4 page.get_query()

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\page.py in get(self, show, proxy, timeout)
    459             self.flags['defer_imageinfo'] = True
    460 
--> 461             self.get_query(False, proxy, timeout)
    462             self.get_parse(False, proxy, timeout)
    463 

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\page.py in get_query(self, show, proxy, timeout)
    574             raise ValueError("get_query needs title or pageid")
    575 
--> 576         self._get('query', show, proxy, timeout)
    577 
    578         return self

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\core.py in _get(self, action, show, proxy, timeout)
    103         self.data['requests'].append(action)
    104 
--> 105         self._set_data(action)
    106 
    107         if show:

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\page.py in _set_data(self, action)
    159         """
    160         if 'query' in action:
--> 161             self._set_query_data(action)
    162         elif action == 'imageinfo':
    163             self._set_imageinfo_data()

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\page.py in _set_query_data(self, action)
    259         set attributes derived from MediaWiki (action=query)
    260         """
--> 261         data = self._load_response(action)
    262         page = data['query']['pages'][0]
    263 

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\core.py in _load_response(self, action)
    119 
    120         try:
--> 121             data = utils.json_loads(response)
    122         except ValueError:
    123             raise ValueError(_query)

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\utils.py in json_loads(data)
     73     python-version safe json.loads
     74     """
---> 75     return json.loads(data, encoding='utf-8')
     76 
     77 

C:\Users\Keenan\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    310     if not isinstance(s, str):
    311         raise TypeError('the JSON object must be str, not {!r}'.format(
--> 312                             s.__class__.__name__))
    313     if s.startswith(u'\ufeff'):
    314         raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",

TypeError: the JSON object must be str, not 'bytes'

**Comment by Kiwibp** [comment] 2017-12-13 21:31
sorry this is what the code should look like. 

```
page = wptools.page('E.T._the_Extra-Terrestrial')
page.get_query()
```

It still gives me the same error message though.

**Comment by Kiwibp** [comment] 2017-12-13 21:33
Just to avoid confusion, here is the output when I ran the above code:

TypeErrorTraceback (most recent call last)
<ipython-input-59-a881fad338ef> in <module>()
      2 # This cell make take a few seconds to run
      3 page = wptools.page('E.T._the_Extra-Terrestrial')
----> 4 page.get_query()

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\page.py in get_query(self, show, proxy, timeout)
    574             raise ValueError("get_query needs title or pageid")
    575 
--> 576         self._get('query', show, proxy, timeout)
    577 
    578         return self

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\core.py in _get(self, action, show, proxy, timeout)
    103         self.data['requests'].append(action)
    104 
--> 105         self._set_data(action)
    106 
    107         if show:

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\page.py in _set_data(self, action)
    159         """
    160         if 'query' in action:
--> 161             self._set_query_data(action)
    162         elif action == 'imageinfo':
    163             self._set_imageinfo_data()

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\page.py in _set_query_data(self, action)
    259         set attributes derived from MediaWiki (action=query)
    260         """
--> 261         data = self._load_response(action)
    262         page = data['query']['pages'][0]
    263 

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\core.py in _load_response(self, action)
    119 
    120         try:
--> 121             data = utils.json_loads(response)
    122         except ValueError:
    123             raise ValueError(_query)

C:\Users\Keenan\Anaconda3\lib\site-packages\wptools\utils.py in json_loads(data)
     73     python-version safe json.loads
     74     """
---> 75     return json.loads(data, encoding='utf-8')
     76 
     77 

C:\Users\Keenan\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    310     if not isinstance(s, str):
    311         raise TypeError('the JSON object must be str, not {!r}'.format(
--> 312                             s.__class__.__name__))
    313     if s.startswith(u'\ufeff'):
    314         raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",

TypeError: the JSON object must be str, not 'bytes'

**Comment by siznax** [comment] 2017-12-13 22:03
Thanks, @Kiwibp . I see what's going on now. Can you try this on the offending computer?

```python
>>> import json
>>> json.loads(b'{"foo":1}')
{'foo': 1}
```

Hopefully that gave you an error. But the following should work for you:

```python
>>> json.loads(b'{"foo":1}'.decode('utf-8'))
{'foo': 1}
```

Can you confirm?

**Comment by Kiwibp** [comment] 2017-12-13 22:05
Thats correct.  The first bit of code gave me the same type error as before and the second bit of code outputs what you got as well.

**Comment by siznax** [comment] 2017-12-13 22:32
The fix for this is available in [v0.4.5](https://github.com/siznax/wptools/releases/tag/v0.4.5) @Kiwibp can you upgrade wptools and confirm the fix? 

You can upgrade wptools likes this:

```shell
$ pip install -U wptools
```

**Comment by Kiwibp** [comment] 2017-12-13 22:38
It works! Thanks so much for your prompt assistance.

**Comment by siznax** [comment] 2017-12-13 22:39
No problem, thanks for your help. Happy hacking!

**Closed by siznax** 2017-12-13 22:39 UTC
Labels: Bug
